---
apiVersion: v2
name: kubernetes-service-netbox-syncer
version: 1.0.1
appVersion: 1.0.0
type: application
home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
