apiVersion: v1
entries:
  kubernetes-service-netbox-syncer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-21T15:32:38.090345+07:00"
    digest: d1db9d4fbfd2bff0404c2b5241883dce25eb29a4ce30a97ee6b58b72f578710d
    home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: kubernetes-service-netbox-syncer
    type: application
    urls:
    - kubernetes-service-netbox-syncer-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-21T15:32:38.089871+07:00"
