apiVersion: v1
entries:
  kubernetes-service-netbox-syncer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-21T15:04:50.41744+07:00"
    digest: ded4314c7b7fda5c969facf58944f7ce2fc47129697d3734db31a49b12637c48
    home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: kubernetes-service-netbox-syncer
    type: application
    urls:
    - kubernetes-service-netbox-syncer-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-21T15:04:50.4167+07:00"
