apiVersion: v1
entries:
  kubernetes-service-netbox-syncer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-21T16:07:55.003687+07:00"
    digest: b0d35f3d11d2dbe7a708b48473adbb48d52e26934edf9afb0e916b589973d205
    home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: kubernetes-service-netbox-syncer
    type: application
    urls:
    - kubernetes-service-netbox-syncer-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-21T16:07:55.00346+07:00"
    digest: d1db9d4fbfd2bff0404c2b5241883dce25eb29a4ce30a97ee6b58b72f578710d
    home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: kubernetes-service-netbox-syncer
    type: application
    urls:
    - kubernetes-service-netbox-syncer-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-21T16:07:55.001947+07:00"
