apiVersion: v1
entries:
  kubernetes-service-netbox-syncer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-19T16:21:40.289896+07:00"
    digest: d23ddab021fd11b6be030adaca62dfd96d94c1d8c5dc90b82147bc3518b874ad
    home: https://github.com/zufardhiyaulhaq/kubernetes-service-netbox-syncer
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: kubernetes-service-netbox-syncer
    type: application
    urls:
    - kubernetes-service-netbox-syncer-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-19T16:21:40.289279+07:00"
